language: shell
install: true

matrix:
  include:

#  - name: "MSVC on Windows"
#    os: windows
#    script:
#    - mkdir build && cd build
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake -G "Visual Studio 15 2017" ..'
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake --build . --config Debug'
#    - ctest -C Debug
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake --build . --config Release'
#    - ctest -C Release

#  - name: "GCC on Windows"
#    os: windows
#    env:
#    - CC="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-gcc"
#    - CXX="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-g++"
#    install:
#    - choco upgrade mingw -y
#    script:
#    - mkdir build-debug && cd build-debug
#    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#    - cmake --build .
#    - ctest -C Debug
#    - cd ..
#    - mkdir build-release && cd build-release
#    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#    - cmake --build .
#    - ctest -C Release

  - name: "Clang on Windows"
    os: windows
    env:
    - CC="/c/Program Files/LLVM/bin/clang"
    - CXX="/c/Program Files/LLVM/bin/clang++"
    install:
    - choco install ninja
    before_script:
      - sudo apt-get update -qq
      - sudo apt-get install libboost-all-dev
    script:
    - ninja --version
    - mkdir build && cd build
    - cmake -G "Ninja" ..

branches:
  only:
    dev

notifications:
  email: false