language: shell
install: true

matrix:
  include:

#  - name: "MSVC on Windows: x86"
#    os: windows
#    script:
#    - mkdir build && cd build
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake -G "Visual Studio 15 2017" ..'
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake --build . --config Debug'
#    - ctest -C Debug
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake --build . --config Release'
#    - ctest -C Release

#  - name: "MSVC on Windows: x64"
#    os: windows
#    script:
#    - mkdir build && cd build
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && cmake -G "Visual Studio 15 2017" ..'
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && cmake --build . --config Debug'
#    - ctest -C Debug
#    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && cmake --build . --config Release'
#    - ctest -C Release

#  - name: "GCC on Windows"
#    os: windows
#    env:
#    - CXX="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-g++"
#    install:
#    - choco upgrade mingw -y
#    script:
#    - mkdir build-debug && cd build-debug
#    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#    - cmake --build .
#    - ctest -C Debug
#    - cd ..
#    - mkdir build-release && cd build-release
#    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#    - cmake --build .
#    - ctest -C Release

  - name: "GCC on Linux"
    os: linux
    dist: bionic
    sudo: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - CXX=g++-8
#    - PATH=/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.rvm/gems/ruby-2.7.0/bin:/home/travis/.rvm/gems/ruby-2.7.0@global/bin:/home/travis/.rvm/rubies/ruby-2.7.0/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin
    install:
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
    - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
    - sudo apt-get update
    - sudo apt-get install cmake
    script:
    - cmake --version
    - echo $PATH

branches:
  only:
    dev

notifications:
  email: false