language: shell
install: true

matrix:
  include:

  - name: "MSVC on Windows: x86"
    os: windows
    script:
    - mkdir build && cd build
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake -G "Visual Studio 15 2017" ..'
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake --build . --config Debug'
    - ctest -C Debug
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86 && cmake --build . --config Release'
    - ctest -C Release

  - name: "MSVC on Windows: x64"
    os: windows
    script:
    - mkdir build && cd build
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && cmake -G "Visual Studio 15 2017" ..'
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && cmake --build . --config Debug'
    - ctest -C Debug
    - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 && cmake --build . --config Release'
    - ctest -C Release

  - name: "GCC on Windows"
    os: windows
    env:
    - CXX="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-g++"
    install:
    - choco upgrade mingw -y
    script:
    - mkdir build-debug && cd build-debug
    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .
    - ctest -C Debug
    - cd ..
    - mkdir build-release && cd build-release
    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    - cmake --build .
    - ctest -C Release

  - name: "gcc on Linux"
    os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - CXX=g++-8
    install:
    - wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
    - tar -zxvf cmake-3.15.2.tar.gz
    - cd cmake-3.15.2
    - ./bootstrap
    - sudo make install
    script:
    - cmake --version

branches:
  only:
    dev

notifications:
  email: false