language: shell
install: true

matrix:
  include:

  - name: "MSVC on Windows"
    os: windows
    # MSVC is already installed on Travis, keep it here just in case we need to use it later
    #install:
    #- choco install visualstudio2017-workload-vctools -y --package-parameters "--no-includeRecommended --add Microsoft.VisualStudio.Component.VC.x86.amd64 --add Microsoft.VisualStudio.Component.Windows10SDK"
    script:
    - mkdir build && cd build
    - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"
    - cmd /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 && cmake -G "Ninja" .. && cmake --build .'


branches:
  only:
    dev